// Generated by https://quicktype.io

export interface DialogResponse {
  results: Results;
  message: string;
}

export interface Results {
  nlp:          NLP;
  qna:          unknown;
  messages:     DMessage[];
  conversation: Conversation;
}

export interface Conversation {
  id:               string;
  language:         string;
  skill:            string;
  skill_occurences: number;
}

export interface DMessage {
  type:     string;
  content:  string;
}

export interface NLP {
  uuid:                string;
  intents:             Intent[];
  entities:            object[];
  language:            string;
  processing_language: string;
  version:             string;
  timestamp:           string;
  status:              number;
  source:              string;
  act:                 string;
  sentiment:           string;
}

export interface Intent {
  slug:        string;
  confidence:  number;
}
